### ISSUE TITLE
ROM Patching for Ampere GPU's

### ISSUE THREAD

**Issue by VFIO-Noob** [wabulu/Single-GPU-passthrough-amd-nvidia#1]
Firstly thank you for your guide as it is very easy to follow but I had a query regarding it.

I have a 3700X system with Arch Linux on the linux-zen kernel and I'm trying to pass through my RTX 3070 to a Windows 10 VM. I was wondering whether it is necessary to do the ROM Step for the Nvidia RTX 3070 as I thought it was only needed for the GTX series pascal gpu's. If it is necessary, is there a chance it can damage / brick my GPU or it is only isolated to the VM as we are not flashing the GPU VBIOS right?

Thanks in advance,
A VFIO Noob

**Comment by wabulu** [comment]
It is not always needed, it varies from one manufacturer to another. 
For my 3060 I needed a patched rom, you may not. There is no way to know in advance. 
Anyway If you are worried about about bricking your card let me calm you down and tell you it's not the same as changing the actual vbios on your card so in no way it can damage it.

**Comment by VFIO-Noob** [comment]
Also, I've opened my GPU's rom file in Okteta and used the Find button to get to the video Char. The guide says to delete EVERYTHING above the U character so that means from the U character all the way to the first part right? I selected by doing Ctrl+Shift+Home and the selection was over 37000 Bytes big so I am unsure if it is necessary to remove such a large amount of stuff from the file.
