### ISSUE TITLE
Script from auto branch errors

### ISSUE THREAD

**Issue by Yaikava** [wabulu/Single-GPU-passthrough-amd-nvidia#11]
![image](https://user-images.githubusercontent.com/83710104/159191891-685c52e0-3a79-4e2c-bbfd-24f6db33bd20.png)

**Comment by wabulu** [comment]
This is a known error, it almost always happen because your distro is not in the database, it is very easy to add it, all you need to do is share the text above the error, it should state your distro id in the message

**Comment by wabulu** [comment]
Also please share your grub file which is usually located in /etc/default/grub

**Comment by Yaikava** [comment]
OS
![image](https://user-images.githubusercontent.com/83710104/159251651-a76346c0-b4cb-4cbb-807c-fcece6ee0dfc.png)
`/etc/default/grub`

```
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
GRUB_TERMINAL_OUTPUT="console"
GRUB_CMDLINE_LINUX="rd.driver.blacklist=nouveau modprobe.blacklist=nouveau nvidia-drm.modeset=1 rhgb quiet rd.driver.blacklist=nouveau modprobe.blacklist=nouveau nvidia-drm.modeset=1"
GRUB_DISABLE_RECOVERY="true"
GRUB_ENABLE_BLSCFG=true
```

pip `pip 21.2.3 from /usr/lib/python3.10/site-packages/pip (python 3.10)`


Whole error again.
![image](https://user-images.githubusercontent.com/83710104/159252328-326eb8ae-9dab-4f89-b2f2-8a9075d58462.png)
