### ISSUE TITLE
Removing scripts

### ISSUE THREAD

**Issue by HarrisonOates** [wabulu/Single-GPU-passthrough-amd-nvidia#15]
So I've struggled with step 4, making the VM. I'm on an Arch Linux system and want to start the process afresh without the changes made by the scripts. Is there an easy way to remove the changes?

**Comment by wabulu** [comment]
Added a script to uninstall everything with commit [1079d43](https://github.com/wabulu/Single-GPU-passthrough-amd-nvidia/commit/1079d43dc036b0d40d882a1f4004fd192c2d9ccc)
