### ISSUE TITLE
sudo bash src/setup.sh not working

### ISSUE THREAD

**Issue by longlostbro** [wabulu/Single-GPU-passthrough-amd-nvidia#19]
Problem:
sudo bash src/setup.sh not working

Error reported:
Syntax error: "(" unexpected

Workaround:
sudo bash ./src/setup.sh

**Comment by wabulu** [comment]
That is really weird, any reason for that ? can anyone else confirm that's the case for them too ?

**Comment by dank-yo** [comment]
> That is really weird, any reason for that ? can anyone else confirm that's the case for them too ?

Yes, i just signed up for an account to comment I had the exact same issue last night on Ubuntu 22.04. I tried modifying some of the bash script but didn't get far.  

`src/setup.sh: 7: Bad substitution`
`src/setup.sh: 47: Syntax error: "(" unexpected (expecting "}")`

**Comment by wabulu** [comment]
> > That is really weird, any reason for that ? can anyone else confirm that's the case for them too ?
> 
> Yes, i just signed up for an account to comment I had the exact same issue last night on Ubuntu 22.04. I tried modifying some of the bash script but didn't get far.
> 
> `src/setup.sh: 7: Bad substitution` `src/setup.sh: 47: Syntax error: "(" unexpected (expecting "}")`

Can you try again now ? I've updated the README.md,  please confirm whether it has fixed your issue or not, if not your bash version might be outdated (most likely not since you are running the latest version of Ubuntu)

**Comment by dank-yo** [comment]
> 

That worked! I think that's the most likely answer because I triple checked and it didn't seem like anything was wrong with the code itself (again, not the best source for that though).

**Comment by wabulu** [comment]
> > 
> 
> That worked! I think that's the most likely answer because I triple checked and it didn't seem like anything was wrong with the code itself (again, not the best source for that though).

Okay, Great ! Closing the issue for now as it seems resolved, if someone have explanation to why src/ doesn't work and ./src/ works please let me know.
